-- ============================================================
-- SISTEM PERSEDIAAN UD TANI SIWI JAYA
-- DATABASE : SUPABASE / POSTGRESQL
-- JUMLAH ENTITAS : 4
-- ============================================================

-- HAPUS SEMUA TABEL LAMA YANG MUNGKIN MASIH ADA
-- agar visualizer Supabase hanya menampilkan 4 tabel utama.
DROP TABLE IF EXISTS public.kategori CASCADE;
DROP TABLE IF EXISTS public.stok CASCADE;
DROP TABLE IF EXISTS public.penjualan CASCADE;
DROP TABLE IF EXISTS public.pembelian CASCADE;
DROP TABLE IF EXISTS public.transaksi_keluar CASCADE;
DROP TABLE IF EXISTS public.transaksi_masuk CASCADE;
DROP TABLE IF EXISTS public.produk CASCADE;
DROP TABLE IF EXISTS public.supplier CASCADE;

-- 1. ENTITAS SUPPLIER
CREATE TABLE supplier (
    id_supplier BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_supplier VARCHAR(100) NOT NULL,
    alamat TEXT,
    telepon VARCHAR(20),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. ENTITAS PRODUK
CREATE TABLE produk (
    id_produk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_supplier BIGINT NOT NULL,
    kode_produk VARCHAR(30) NOT NULL UNIQUE,
    nama_produk VARCHAR(100) NOT NULL,
    kategori VARCHAR(50),
    satuan VARCHAR(30) NOT NULL,
    harga_beli NUMERIC(15,2) NOT NULL DEFAULT 0,
    harga_jual NUMERIC(15,2) NOT NULL DEFAULT 0,
    stok INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT fk_produk_supplier
        FOREIGN KEY (id_supplier)
        REFERENCES supplier(id_supplier)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_harga_beli CHECK (harga_beli >= 0),
    CONSTRAINT chk_harga_jual CHECK (harga_jual >= 0),
    CONSTRAINT chk_stok CHECK (stok >= 0)
);

-- 3. ENTITAS TRANSAKSI MASUK
CREATE TABLE transaksi_masuk (
    id_masuk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_produk BIGINT NOT NULL,
    tanggal DATE NOT NULL DEFAULT CURRENT_DATE,
    jumlah INTEGER NOT NULL,
    harga_beli NUMERIC(15,2) NOT NULL DEFAULT 0,
    total NUMERIC(15,2) GENERATED ALWAYS AS (jumlah * harga_beli) STORED,
    created_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT fk_masuk_produk
        FOREIGN KEY (id_produk)
        REFERENCES produk(id_produk)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_jumlah_masuk CHECK (jumlah > 0),
    CONSTRAINT chk_harga_masuk CHECK (harga_beli >= 0)
);

-- 4. ENTITAS TRANSAKSI KELUAR
CREATE TABLE transaksi_keluar (
    id_keluar BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_produk BIGINT NOT NULL,
    tanggal DATE NOT NULL DEFAULT CURRENT_DATE,
    jumlah INTEGER NOT NULL,
    harga_jual NUMERIC(15,2) NOT NULL DEFAULT 0,
    total NUMERIC(15,2) GENERATED ALWAYS AS (jumlah * harga_jual) STORED,
    created_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT fk_keluar_produk
        FOREIGN KEY (id_produk)
        REFERENCES produk(id_produk)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_jumlah_keluar CHECK (jumlah > 0),
    CONSTRAINT chk_harga_keluar CHECK (harga_jual >= 0)
);

-- INDEX
CREATE INDEX idx_produk_supplier ON produk(id_supplier);
CREATE INDEX idx_masuk_produk ON transaksi_masuk(id_produk);
CREATE INDEX idx_masuk_tanggal ON transaksi_masuk(tanggal);
CREATE INDEX idx_keluar_produk ON transaksi_keluar(id_produk);
CREATE INDEX idx_keluar_tanggal ON transaksi_keluar(tanggal);

-- DATA AWAL SUPPLIER
INSERT INTO supplier (nama_supplier, alamat, telepon) VALUES
('PT Tani Makmur', 'Jl. Raya Pertanian No. 10', '081234567890'),
('CV Agro Sejahtera', 'Jl. Padi No. 25', '081298765432'),
('UD Sumber Tani', 'Jl. Kebun Raya No. 15', '082112223333');

-- DATA AWAL PRODUK
INSERT INTO produk (
    id_supplier,
    kode_produk,
    nama_produk,
    kategori,
    satuan,
    harga_beli,
    harga_jual,
    stok
) VALUES
(1, 'P001', 'Pupuk Urea', 'Pupuk', 'Kg', 2500, 3000, 100),
(2, 'P002', 'Pupuk NPK', 'Pupuk', 'Kg', 4500, 5500, 75),
(3, 'P003', 'Benih Jagung', 'Benih', 'Kg', 35000, 42000, 25);

-- CEK HASIL
SELECT * FROM supplier;
SELECT * FROM produk;
SELECT * FROM transaksi_masuk;
SELECT * FROM transaksi_keluar;